services:
  db:
    image: postgres:12
    container_name: incx-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - incx-network

  minio:
    image: minio/minio
    container_name: incx-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    command: server /data --console-address ":9001" --address ":9000"
    volumes:
      - miniodata:/var/lib/minio/data
    networks:
      - incx-network

  backend:
    restart: on-failure
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: incx-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${BACKEND_PORT}:8080"
    develop:
      watch:
        - action: rebuild
          path: .
          target: /code
    networks:
      - incx-network
  
  frontend:
    restart: on-failure
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: incx-frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          target: /app
    networks:
      - incx-network

volumes:
  pgdata:
  miniodata:

networks:
  incx-network:
    driver: bridge